export interface WordCategory {
  id: string;
  label: string;
  icon: string;
  words: string[];
}

export const WORD_CATALOG: WordCategory[] = [
  {
    id: "peliculas",
    label: "Películas",
    icon: "film-outline",
    words: [
      "Avatar",
      "Titanic",
      "Matrix",
      "Inception",
      "Interstellar",
      "Joker",
      "Gladiator",
      "Parasite",
      "Coco",
      "Frozen",
      "Lion King",
      "Shrek",
      "Toy Story",
      "Up",
      "Transformers",
      "Dune",
      "Oppenheimer",
      "Barbie",
    ],
  },
  {
    id: "comidas",
    label: "Comidas",
    icon: "restaurant-outline",
    words: [
      "Pizza",
      "Sushi",
      "Tacos",
      "Ramen",
      "Hamburguesa",
      "Paella",
      "Lasaña",
      "Ceviche",
      "Arepa",
      "Empanada",
      "Shawarma",
      "Tacos",
      "Donuts",
      "Pastel",
      "Risotto",
      "Crepes",
      "Waffle",
      "Sopa",
    ],
  },
  {
    id: "deportes",
    label: "Deportes",
    icon: "football-outline",
    words: [
      "Fútbol",
      "Baloncesto",
      "Tenis",
      "Natación",
      "Ciclismo",
      "Boxeo",
      "Volleyball",
      "Baseball",
      "Golf",
      "Rugby",
      "Atletismo",
      "Escalada",
      "Surf",
      "Esquí",
      "Judo",
      "Esgrima",
      "Polo",
      "Fórmula 1",
    ],
  },
  {
    id: "animales",
    label: "Animales",
    icon: "paw-outline",
    words: [
      "Elefante",
      "Tigre",
      "Delfín",
      "Águila",
      "Pingüino",
      "Koala",
      "Camello",
      "Pulpo",
      "Panda",
      "Cocodrilo",
      "Flamenco",
      "Murciélago",
      "Tortuga",
      "Lobo",
      "Canguro",
      "Foca",
      "Jaguar",
      "Cóndor",
    ],
  },
  {
    id: "paises",
    label: "Países",
    icon: "earth-outline",
    words: [
      "Japón",
      "Brasil",
      "Egipto",
      "Noruega",
      "India",
      "México",
      "Australia",
      "Turquía",
      "Colombia",
      "Grecia",
      "Tailandia",
      "Canadá",
      "Marruecos",
      "Perú",
      "Suecia",
      "Nigeria",
      "Argentina",
      "Portugal",
    ],
  },
  {
    id: "musica",
    label: "Música",
    icon: "musical-notes-outline",
    words: [
      "Jazz",
      "Salsa",
      "Reggaeton",
      "Rock",
      "Cumbia",
      "Flamenco",
      "Opera",
      "Hip Hop",
      "Bachata",
      "Tango",
      "Merengue",
      "Blues",
      "Vallenato",
      "Bossa Nova",
      "Trap",
      "Reggae",
      "Soul",
      "Funk",
    ],
  },
  {
    id: "profesiones",
    label: "Profesiones",
    icon: "briefcase-outline",
    words: [
      "Astronauta",
      "Chef",
      "Bombero",
      "Arqueólogo",
      "Piloto",
      "Cirujano",
      "Detective",
      "Diplomático",
      "Marinero",
      "Mago",
      "Locutor",
      "Sommelier",
      "Taxidermista",
      "Cartógrafo",
      "Domador",
      "Buzo",
      "Espía",
      "Ingeniero",
    ],
  },
  {
    id: "lugares",
    label: "Lugares",
    icon: "location-outline",
    words: [
      "Coliseo",
      "Machu Picchu",
      "Sahara",
      "Amazonia",
      "Times Square",
      "Everest",
      "Gran Barrera",
      "Stonehenge",
      "Angkor Wat",
      "Alhambra",
      "Antártida",
      "Venecia",
      "Dubái",
      "Petra",
      "Pompeya",
      "Bali",
      "Patagonia",
      "Maldivas",
    ],
  },
];

export function getRandomWord(
  categoryId: string,
  usedWords: string[],
): string | null {
  const category = WORD_CATALOG.find((c) => c.id === categoryId);
  if (!category) return null;
  const available = category.words.filter((w) => !usedWords.includes(w));
  if (available.length === 0) return null;
  return available[Math.floor(Math.random() * available.length)];
}
